// SPDX-License-Identifier: Apache-2.0

#ifndef MOONLIGHT_HAPTICS_VERSION_H
#define MOONLIGHT_HAPTICS_VERSION_H

#define MOONLIGHT_HAPTICS_VERSION_MAJOR 0
#define MOONLIGHT_HAPTICS_VERSION_MINOR 7
#define MOONLIGHT_HAPTICS_VERSION_PATCH 0
#define MOONLIGHT_HAPTICS_VERSION_STRING "0.7.0"
#define MOONLIGHT_HAPTICS_PARAMETER_SET_VERSION "action-rpg-p4g-v6-dialogue"

#define MOONLIGHT_HAPTICS_ABI_VERSION 2u

#endif // MOONLIGHT_HAPTICS_VERSION_H
